name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        imgtag:
          - "python:3.7-buster"
          - "python:3.8-buster"
        tornado_ver:
          - "4.5.3"
          - "5.1.1"
          - "6.0.4"
        exclude:
          - imgtag: "python:2.7-buster"
            tornado_ver: "6.0.4"

    container: "${{matrix.imgtag}}"
    steps:
      - name: Install System Dependencies
        run: |
          apt-get -q -y update
          apt-get -q -y install libsnappy-dev
    